### ISSUE TITLE
Todo list MSP Technical board

### ISSUE THREAD

**Issue by laurentiustamate94** [microsoft-dx/aspnet-fundamentals#4]
- [ ] document [aspnet01](https://github.com/microsoft-dx/aspnet-fundamentals/tree/master/aspnet01%20-%20WebIntroduction)
- [ ] document [aspnet02](https://github.com/microsoft-dx/aspnet-fundamentals/tree/master/aspnet02%20-%20HelloWebApi)
- [ ] document [aspnet03](https://github.com/microsoft-dx/aspnet-fundamentals/tree/master/aspnet03%20-%20SimpleProductsApi)
- [ ] document [aspnet04](https://github.com/microsoft-dx/aspnet-fundamentals/tree/master/aspnet04%20-%20SimpleTokenAuthentication)
- [ ] document [aspnet05](https://github.com/microsoft-dx/aspnet-fundamentals/tree/master/aspnet05%20-%20BasicHitCounter)
- [ ] document [aspnet06](https://github.com/microsoft-dx/aspnet-fundamentals/tree/master/aspnet06%20-%20MapLocator)
- [ ] document [aspnet07](https://github.com/microsoft-dx/aspnet-fundamentals/tree/master/aspnet07%20-%20ChatApplication)
- [ ] create root README to connect all applications

All documentations need to be done similar to the [csharp-fundamentals repo](https://github.com/microsoft-dx/csharp-fundamentals)
